name: Create Release Zip
on:
  push:
    tags:
      - 'v*' # Triggers when you push a tag like v1.4.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip Folder
        run: zip -r VortexPlus.zip . -x "*.git*" ".github*" # Zips everything except git files
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: VortexPlus.zip
