name: Create Release Zip
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Crucial: Allows the action to create releases
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Folder
        run: zip -r VortexPro.zip . -x "*.git*" ".github*"

      - name: Create Release
        uses: softprops/action-gh-release@v2  # Updated to v2
        with:
          files: VortexPro.zip